version: '3.7'
services:
  database:
    container_name: mongo_db_container
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27019:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: